### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by fredaas** [InteractiveComputerGraphics/SPlisHSPlasH#22]
Building different targets with `make` after running `cmake` generates a myriad of different error messages. Some are compiler related, e.g. `#error` due to lacking c++11 support, and some are related to library specific function calls, e.g. `omp_get_max_threads` due to not linking with `-fopenmp`. None of these errors are justified however, as the target system does provide support for the error messages just mentioned. Below is a selection of make commands and some of their related error messages that I get on the target system: Linux x86_64, 4.4.0-135-generic, Ubuntu 16.04, g++ 5.4.0.

Error: `make`
```
error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```
Error: `make StaticBoundaryDemo`
```
error: ‘omp_get_max_threads’ was not declared in this scope
```
Error: `make DynamicBoundaryDemo`
```
error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```
Error: `make SPlisHSPlasH`
```
error: ‘omp_get_max_threads’ was not declared in this scope
```

These are purely build related, as the support is there, the build system just don't detect the required tools.

A pointer (no pun intended) in the right direction would be much appreciated.

**Comment by janbender** [comment]
The openmp errors should be fixed in the current version. The problem was a missing compiler flag in the debug build. However, I cannot reproduce the C++11 problem.

**Comment by practisedaybyday** [comment]
So,how to solve the openmp errors?

**Comment by fredaas** [comment]
Okay, so the errors related to openmp are gone now, thanks! However, I still get the following error:
```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```
I've tried setting the cmake environment variables to reflect the ISO C++ 2011 standard, but no luck. It should be noted that I don't have much experience with cmake, so it's possible I'm overlooking something trivial. I'm building the project using:
```
cmake CMakeLists.txt -DCMAKE_CXX_COMPILER="/usr/bin/g++" -DCMAKE_CXX_FLAGS="-std=c++11" -DCMAKE_CXX_STANDARD=11
```

**Comment by janbender** [comment]
This is strange since I set the C++11 standard in the common.cmake file: 

set(CMAKE_CXX_STANDARD 11)

**Comment by fredaas** [comment]
So, I' building from a new system now: Linux x86_64, 4.15.0-42-generic, Ubuntu 18.04.01, g++ 7.3.0.

ISO C++ problems appears to be gone, however the OpenMP errors are back:
```
SPlisHSPlasH/Utilities/PoissonDiskSampling.cpp:127:25: error: ‘omp_get_max_threads’ was not declared in this scope
```
I'm giving up on this now, maybe next year. Merry Christmas :christmas_tree:

**Comment by janbender** [comment]
Try to build it in release mode: 

cmake -DCMAKE_BUILD_TYPE=Release

**Comment by fredaas** [comment]
Building with `cmake -DCMAKE_BUILD_TYPE=Release` works. Thanks for helping! Can't wait to play with this during Christmas holidays :smiley:

Closing...
